apiVersion: v1
kind: Service
metadata:
  name: wildfly-service
spec:
  type: NodePort
  selector:
    app: wildfly
  ports:
    - name: app
      port: 8080
      targetPort: 8080
      nodePort: 8080
    - name: admin
      port: 9990
      targetPort: 9990
      nodePort: 9990

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 2
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: mcweenjr/hello-world-war:latest
        command: ["/opt/jboss/wildfly/bin/standalone.sh"]
        args: ["-b", "0.0.0.0", "-bmanagement", "0.0.0.0" ]
        ports:
          - containerPort: 8080
          - containerPort: 9990
